from pathlib import Path
p=Path('ARCANA_BATTLES.html')
s=p.read_text(encoding='utf-8')
def rep(a,b):
    global s
    if s.count(a)!=1: raise SystemExit(f'expected 1 match, got {s.count(a)}: {a[:100]!r}')
    s=s.replace(a,b,1)
rep('''    setLock(u, enemy) {''','''    setLock(u, enemy, silent = false) {''')
rep('''      Log.add(`${u.name}: LOCK-ON → ${enemy.name}${u.ranged ? ' [RANGED]' : ''}`);\n      return true;''','''      if (!silent) Log.add(`${u.name}: LOCK-ON → ${enemy.name}${u.ranged ? ' [RANGED]' : ''}`);\n      return true;''')
rep('''      UI.updateSelectedInfo();\n      Log.add(`SCHIERAMENTO: ${side === 'blue' ? 'BLU' : 'ROSSO'}`);\n    },''','''      UI.updateSelectedInfo();\n      if (State.battle.active && !State.deployment.active) ArmyAI.setPlayerSide(side);\n      Log.add(`SCHIERAMENTO: ${side === 'blue' ? 'BLU' : 'ROSSO'}`);\n    },''')
marker='''  const UI = {\n    setTimeScale(scale) {'''
army='''  // ============================================================\n  // ARMY AI v0.1 — one strategic refresh every 5 simulated seconds.\n  // Base order: every free AI unit attacks its nearest enemy.\n  // A single refresh may therefore issue the same strategic order to many units.\n  // ============================================================\n  const ArmyAI = {\n    opposite(side) { return side === 'blue' ? 'red' : 'blue'; },\n\n    aiSide() { return this.opposite(State.battle.playerSide); },\n\n    releaseSide(side) {\n      for (const u of Units.alive(side)) {\n        if (u.status.routing || u.order.kind === 'retreat' || Engagements.hasAny(u)) continue;\n        if (u.order.kind === 'lock' || u.order.kind === 'ai') Orders.clear(u);\n        if (u.ranged) {\n          u.ranged.approachTargetId = null;\n          u.ranged.targetId = null;\n          u.ranged.clock = 0;\n        }\n      }\n    },\n\n    setPlayerSide(side) {\n      if (!['blue','red'].includes(side) || State.battle.playerSide === side) return false;\n      State.battle.playerSide = side;\n      this.releaseSide(side);\n      State.armyAI.lastRefreshAt = -Infinity;\n      Log.add(`DEV CONTROLLO → ${side.toUpperCase()} | Army AI passa a ${this.aiSide().toUpperCase()}`);\n      this.refresh(true);\n      return true;\n    },\n\n    issueAttackNearest(u) {\n      if (!u?.status?.alive || u.status.routing || u.order.kind === 'retreat' || Engagements.hasAny(u)) return 'skip';\n      const found = AI.nearestEnemy(u);\n      const enemy = found?.enemy || null;\n      if (!enemy) {\n        if (u.order.kind === 'lock' || u.order.kind === 'ai') Orders.clear(u);\n        return 'none';\n      }\n      if (u.order.lockTargetId === enemy.id && (u.order.kind === 'lock' || u.order.kind === 'ai')) return 'same';\n      return Orders.setLock(u, enemy, true) ? 'new' : 'skip';\n    },\n\n    refresh(force = false) {\n      if (!State.armyAI.enabled || !State.battle.active || State.battle.ended || State.deployment.active) return false;\n      if (!force && State.simTime - State.armyAI.lastRefreshAt < CFG.ARMY_AI_REFRESH_S) return false;\n      State.armyAI.lastRefreshAt = State.simTime;\n      State.armyAI.refreshCount += 1;\n\n      const side = this.aiSide();\n      let issued = 0, same = 0, skipped = 0;\n      for (const u of Units.alive(side)) {\n        const r = this.issueAttackNearest(u);\n        if (r === 'new') issued++;\n        else if (r === 'same') same++;\n        else skipped++;\n      }\n      Log.add(`🤖 ARMY AI ${side.toUpperCase()} #${State.armyAI.refreshCount}: ATTACCA IL PIÙ VICINO | nuovi ${issued} · confermati ${same} · non assegnabili ${skipped}`);\n      return true;\n    },\n\n    update() {\n      this.refresh(false);\n    }\n  };\n\n  const UI = {\n    setTimeScale(scale) {'''
rep(marker,army)
p.write_text(s,encoding='utf-8')
