from pathlib import Path
p=Path('ARCANA_BATTLES.html')
s=p.read_text(encoding='utf-8')
def rep(a,b):
    global s
    if s.count(a)!=1: raise SystemExit(f'expected 1 match, got {s.count(a)}: {a[:80]!r}')
    s=s.replace(a,b,1)
rep('<title>ARCANA — Campal Battle Lab v0.85.0</title>','<title>ARCANA — Campal Battle Lab v0.86.0</title>')
rep('<strong>ARCANA — CAMPAL BATTLE LAB v0.85.0</strong>','<strong>ARCANA — CAMPAL BATTLE LAB v0.86.0</strong>')
rep('''      <div class="setup-mode-note" id="setupModeNote">AUTO usa Doctrine Engine: genera prima le unità, poi sceglie la dottrina in base a composizione, campo e ruolo ATT/DEF.</div>\n    </div>\n\n    <div class="setup-summary">''','''      <div class="setup-mode-note" id="setupModeNote">AUTO usa Doctrine Engine: genera prima le unità, poi sceglie la dottrina in base a composizione, campo e ruolo ATT/DEF.</div>\n    </div>\n\n    <div class="setup-section">\n      <span class="setup-label">RUOLO GIOCATORE · BLU ALL'AVVIO</span>\n      <div class="setup-modes" id="setupRoles">\n        <button type="button" data-role="random" class="active">CASUALE<small>ATT o DEF assegnato a inizio partita</small></button>\n        <button type="button" data-role="attack">ATTACCANTE<small>il BLU deve ottenere la vittoria entro il tempo</small></button>\n        <button type="button" data-role="defend">DIFENSORE<small>il BLU vince se resiste fino al limite</small></button>\n      </div>\n      <div class="setup-mode-note" id="setupRoleNote">In DEV puoi ancora cambiare fazione durante la battaglia; il ruolo ATT/DEF resta legato al colore assegnato all'avvio.</div>\n    </div>\n\n    <div class="setup-summary">''')
rep('''    <div class="setup-footnote">v0.85 · Step 1/3 — AUTO usa Doctrine Engine; MIRRORED e CUSTOM aprono il Deployment Builder.</div>''','''    <div class="setup-footnote">v0.86 · Step 1/3 — ruolo ATT/DEF + Army AI refresh 5s + limite battaglia 600s.</div>''')
rep('''    setupModeNote: document.getElementById('setupModeNote'),\n    setupModeSummary: document.getElementById('setupModeSummary'),\n    setupPointsSummary: document.getElementById('setupPointsSummary'),''','''    setupModeNote: document.getElementById('setupModeNote'),\n    setupModeSummary: document.getElementById('setupModeSummary'),\n    setupRoles: document.getElementById('setupRoles'),\n    setupRoleNote: document.getElementById('setupRoleNote'),\n    setupPointsSummary: document.getElementById('setupPointsSummary'),''')
rep('''    TERRAIN_SOFT_EDGE_U: 0.75, // fascia visibile esterna: accidentata ma non collider duro\n    FORMATIONS:''','''    TERRAIN_SOFT_EDGE_U: 0.75, // fascia visibile esterna: accidentata ma non collider duro\n    ARMY_AI_REFRESH_S: 5,\n    BATTLE_TIME_LIMIT_S: 600,\n    FORMATIONS:''')
rep('''      points: 1000,\n      mode: 'auto',\n      mirrorArmy: false,''','''      points: 1000,\n      mode: 'auto',\n      role: 'random',\n      mirrorArmy: false,''')
rep('''    doctrine: {\n      roles: { blue: null, red: null },\n      selected: { blue: null, red: null },\n      scores: { blue: [], red: [] },\n      terrain: { blue: null, red: null },\n      compositions: { blue: [], red: [] }\n    },\n    battle:''','''    doctrine: {\n      roles: { blue: null, red: null },\n      selected: { blue: null, red: null },\n      scores: { blue: [], red: [] },\n      terrain: { blue: null, red: null },\n      compositions: { blue: [], red: [] }\n    },\n    armyAI: {\n      enabled: true,\n      lastRefreshAt: -Infinity,\n      refreshCount: 0\n    },\n    battle:''')
p.write_text(s,encoding='utf-8')
