from pathlib import Path
p=Path('ARCANA_BATTLES.html')
s=p.read_text(encoding='utf-8')
def rep(a,b):
    global s
    if s.count(a)!=1: raise SystemExit(f'expected 1 match, got {s.count(a)}: {a[:100]!r}')
    s=s.replace(a,b,1)
rep('''      const attacker = Math.random() < 0.5 ? 'blue' : 'red';\n      State.doctrine.roles = {\n        blue: attacker === 'blue' ? 'attack' : 'defend',\n        red: attacker === 'red' ? 'attack' : 'defend'\n      };''','''      // I ruoli vengono risolti dal setup partita. Fallback solo per chiamate DEV dirette.\n      if (!State.doctrine.roles.blue || !State.doctrine.roles.red) {\n        const attacker = Math.random() < 0.5 ? 'blue' : 'red';\n        State.doctrine.roles = {\n          blue: attacker === 'blue' ? 'attack' : 'defend',\n          red: attacker === 'red' ? 'attack' : 'defend'\n        };\n      }''')
marker='''    setMode(mode) {\n      if (!['auto','mirrored','custom'].includes(mode)) mode = 'auto';'''
insert='''    roleCopy(role) {\n      if (role === 'attack') return { summary:'ATTACCANTE', note:'BLU = ATTACCANTE · ROSSO = DIFENSORE.' };\n      if (role === 'defend') return { summary:'DIFENSORE', note:'BLU = DIFENSORE · ROSSO = ATTACCANTE.' };\n      return { summary:'CASUALE', note:'Il ruolo del BLU viene estratto a inizio partita; il ROSSO riceve automaticamente il ruolo opposto.' };\n    },\n\n    setRole(role) {\n      if (!['random','attack','defend'].includes(role)) role = 'random';\n      State.battleSetup.role = role;\n      this.sync();\n    },\n\n    resolveRoles() {\n      let blueRole = State.battleSetup.role;\n      if (blueRole === 'random') blueRole = Math.random() < 0.5 ? 'attack' : 'defend';\n      const redRole = blueRole === 'attack' ? 'defend' : 'attack';\n      State.doctrine.roles = { blue:blueRole, red:redRole };\n      State.battle.playerSide = 'blue';\n      return { blue:blueRole, red:redRole };\n    },\n\n    setMode(mode) {\n      if (!['auto','mirrored','custom'].includes(mode)) mode = 'auto';'''
rep(marker,insert)
rep('''      const copy = this.modeCopy(State.battleSetup.mode);\n      DOM.setupModeSummary.textContent = copy.summary;\n      DOM.setupModeNote.textContent = copy.note;\n      DOM.setupModes.querySelectorAll('[data-mode]').forEach(btn => {\n        btn.classList.toggle('active', btn.dataset.mode === State.battleSetup.mode);\n      });''','''      const copy = this.modeCopy(State.battleSetup.mode);\n      const roleCopy = this.roleCopy(State.battleSetup.role);\n      DOM.setupModeSummary.textContent = `${copy.summary} · ${roleCopy.summary}`;\n      DOM.setupModeNote.textContent = copy.note;\n      DOM.setupRoleNote.textContent = `${roleCopy.note} In DEV puoi ancora cambiare fazione durante la battaglia.`;\n      DOM.setupModes.querySelectorAll('[data-mode]').forEach(btn => {\n        btn.classList.toggle('active', btn.dataset.mode === State.battleSetup.mode);\n      });\n      DOM.setupRoles.querySelectorAll('[data-role]').forEach(btn => {\n        btn.classList.toggle('active', btn.dataset.role === State.battleSetup.role);\n      });''')
rep('''      State.battleSetup.points = this.sanitizePoints(\n        DOM.customPointsInput.value ? DOM.customPointsInput.value : State.battleSetup.points\n      );\n      State.battleSetup.configured = true;''','''      State.battleSetup.points = this.sanitizePoints(\n        DOM.customPointsInput.value ? DOM.customPointsInput.value : State.battleSetup.points\n      );\n      const resolvedRoles = this.resolveRoles();\n      State.battleSetup.configured = true;''')
rep('''      Log.add(`SETUP: ${State.battleSetup.points} PT | mode ${State.battleSetup.mode.toUpperCase()}`);''','''      Log.add(`SETUP: ${State.battleSetup.points} PT | mode ${State.battleSetup.mode.toUpperCase()} | BLU ${resolvedRoles.blue.toUpperCase()} · ROSSO ${resolvedRoles.red.toUpperCase()}`);''')
rep('''      DOM.setupModes.querySelectorAll('[data-mode]').forEach(btn => {\n        btn.addEventListener('click', () => this.setMode(btn.dataset.mode));\n      });\n      DOM.customPointsInput.addEventListener('input', () => {''','''      DOM.setupModes.querySelectorAll('[data-mode]').forEach(btn => {\n        btn.addEventListener('click', () => this.setMode(btn.dataset.mode));\n      });\n      DOM.setupRoles.querySelectorAll('[data-role]').forEach(btn => {\n        btn.addEventListener('click', () => this.setRole(btn.dataset.role));\n      });\n      DOM.customPointsInput.addEventListener('input', () => {''')
p.write_text(s,encoding='utf-8')
