from pathlib import Path
p=Path('ARCANA_BATTLES.html')
s=p.read_text(encoding='utf-8')
def rep(a,b):
    global s
    if s.count(a)!=1: raise SystemExit(f'expected 1 match, got {s.count(a)}: {a[:100]!r}')
    s=s.replace(a,b,1)
rep('''      State.battle.result = null;\n      State.battle.armyCollapse = { blue: false, red: false };\n      this.hideResult();''','''      State.battle.result = null;\n      State.battle.playerSide = 'blue';\n      State.battle.armyCollapse = { blue: false, red: false };\n      State.armyAI.lastRefreshAt = -Infinity;\n      State.armyAI.refreshCount = 0;\n      this.hideResult();''')
rep('''    showResult(result) {''','''    showResult(result, leadOverride = null) {''')
rep('''      const outcomeLead = result === 'victory'\n        ? 'Non ci sono più unità nemiche attive sul campo.'\n        : result === 'defeat'\n          ? 'Non ci sono più unità alleate attive sul campo.'\n          : 'Entrambi gli eserciti non hanno più unità attive sul campo.';''','''      const outcomeLead = leadOverride || (result === 'victory'\n        ? 'Non ci sono più unità nemiche attive sul campo.'\n        : result === 'defeat'\n          ? 'Non ci sono più unità alleate attive sul campo.'\n          : 'Entrambi gli eserciti non hanno più unità attive sul campo.');''')
marker='''    checkOutcome() {\n      if (!State.battle.active || State.battle.ended || State.deployment.active) return;'''
insert='''    defenderSide() {\n      if (State.doctrine.roles.blue === 'defend') return 'blue';\n      if (State.doctrine.roles.red === 'defend') return 'red';\n      return State.doctrine.roles.blue === 'attack' ? 'red' : 'blue';\n    },\n\n    showSideWinner(winnerSide, reason) {\n      const result = winnerSide === State.battle.playerSide ? 'victory' : 'defeat';\n      const label = winnerSide === 'blue' ? 'BLU' : 'ROSSO';\n      this.showResult(result, `${reason} · Vincitore: ${label}.`);\n    },\n\n    checkTimeLimit() {\n      if (!State.battle.active || State.battle.ended || State.deployment.active) return;\n      if (State.simTime < CFG.BATTLE_TIME_LIMIT_S) return;\n      const defender = this.defenderSide();\n      Log.add(`⏱ TEMPO SCADUTO ${Math.floor(CFG.BATTLE_TIME_LIMIT_S/60)}:00 → vittoria DIFENSORE ${defender.toUpperCase()}`);\n      this.showSideWinner(defender, `Tempo massimo di ${Math.floor(CFG.BATTLE_TIME_LIMIT_S/60)} minuti raggiunto: il DIFENSORE mantiene il campo`);\n    },\n\n    checkOutcome() {\n      if (!State.battle.active || State.battle.ended || State.deployment.active) return;'''
rep(marker,insert)
rep('''      DOM.log.textContent = `${restoredDeployment ? 'Battaglia resettata dallo schieramento.' : 'Battaglia 3 vs 3 resettata.'}\\nARCHITETTURA v0.85: ${State.battleSetup.points} PT · Mirror Army ${State.battleSetup.mirrorArmy ? 'ON' : 'OFF'} · Mirror Deployment ${State.battleSetup.mirrorDeployment ? 'ON' : 'OFF'} · campo 90×60U + bordocampo 10U · deployment sui lati lunghi · terreni random al centro (laghetto, muro, altura, bosco, strada, terreno difficile).`;''','''      DOM.log.textContent = `${restoredDeployment ? 'Battaglia resettata dallo schieramento.' : 'Battaglia 3 vs 3 resettata.'}\\nARCHITETTURA v0.86: ${State.battleSetup.points} PT · BLU ${(State.doctrine.roles.blue || '—').toUpperCase()} · ROSSO ${(State.doctrine.roles.red || '—').toUpperCase()} · Army AI ${CFG.ARMY_AI_REFRESH_S}s · limite ${CFG.BATTLE_TIME_LIMIT_S}s · campo 90×60U + bordocampo 10U.`;''')
rep('''    update(dt) {\n      State.units.forEach(Formations.update);\n      State.units.forEach(AI.update.bind(AI));''','''    update(dt) {\n      ArmyAI.update();\n      State.units.forEach(Formations.update);\n      State.units.forEach(AI.update.bind(AI));''')
rep('''      Battle.checkArmyCollapse();\n      Battle.checkOutcome();\n    },''','''      Battle.checkArmyCollapse();\n      Battle.checkOutcome();\n      Battle.checkTimeLimit();\n    },''')
rep('''  window.__ARCANA_DEBUG__ = { State, Units, Geometry, Terrain, AI, Movement, Orders, Engagements, Collision, Simulation, Selection, CFG, Pathfinder, Combat, Morale, Resources, Battle, BattleSetup, Deployment, DoctrineEngine };''','''  window.__ARCANA_DEBUG__ = { State, Units, Geometry, Terrain, AI, ArmyAI, Movement, Orders, Engagements, Collision, Simulation, Selection, CFG, Pathfinder, Combat, Morale, Resources, Battle, BattleSetup, Deployment, DoctrineEngine };''')
p.write_text(s,encoding='utf-8')
